### ISSUE TITLE
Pressing TAB to autofill a command doesn't place the cursor at the end

### ISSUE THREAD

**Issue by ndumais** [anarkila/DeveloperConsole#7]
This is a bit of a weird one, cause looking at the code, it seems like you already put in something for that. 
I tried fixing it without luck, adding a long enough delay seems to do something, but there's definitely something I don't get.

If you autofill a command pressing tab the cursor will stay in the same position, example:

![image](https://user-images.githubusercontent.com/48096495/202820358-dc5951fb-5f34-4aaf-b620-8f751e662ec6.png)

![image](https://user-images.githubusercontent.com/48096495/202820385-b6511b3e-5565-436e-9bf0-c6e7e1d3ce81.png)

This is a bit annoying since the expected behavior would be to be able to type arguments right away, not sure if there should be a space automatically added at the end also, probably not needed, but I'm not sure what's the expected behaviour there. Thanks as always!

**Comment by anarkila** [comment]
This is weird because this should work. Which Unity version are you using?

**Comment by ndumais** [comment]
> This is weird because this should work. Which Unity version are you using?

Using 2020.3.32f1 here. Don't think I've witnessed it working on that version, I assume it's working for you?

**Comment by anarkila** [comment]
I wasn't able to replicate this issue with Unity 2019.3.16f1, 2020.3.42f1 or 2021.3.12f1 versions. Does this happen with every command you try? Does this happen in every scene and in the example scenes?

**Comment by ndumais** [comment]
Just tested opening the project, from the dev branch to test outside of my context, but it seems like the prefab is broken, scripts are no longer linked somehow.

![image](https://user-images.githubusercontent.com/48096495/204096325-310ff01d-8bb1-48f0-9c0c-957f2ba92bbb.png)

Also, the issue is when you press Tab (autofill), but everything works fine with previous command (arrowup).

**Comment by anarkila** [comment]
Oops, I had not committed Unity .meta files which leads to missing references. This is now fixed. Both main and dev branches should now work properly if you clone the project and open it with Unity.

**Comment by ndumais** [comment]
Does seem to work on 2020.3.32f1 with the test scene. Might do some more testing at some point, I have a feeling it might have to do with frames, which could explain why it only happens in a bigger project. Note that SceneA (and also probably B and C) still have an Event System which makes it print a warning in console (since there are two in the scenes with the prefab fix).

On another note, check closed [issue #6](https://github.com/anarkila/DeveloperConsole/issues/6), seems like there's something wrong with it.

**Comment by anarkila** [comment]
I removed the EventSystem component from DeveloperConsole.prefab and instead added editor (OnValidate) check whether scene has EventSystem or not. If EventSystem component does not exists, then new GameObject is created and the component is added to it https://github.com/anarkila/DeveloperConsole/commit/ebc7e985aaf5dd8af8a5c18d575ac0cbd5f2ead0

**Comment by anarkila** [comment]
>Does seem to work on 2020.3.32f1 with the test scene. Might do some more testing at some point, I have a feeling it might have to do with frames, which could explain why it only happens in a bigger project. 

I found few posts on Unity forums that have similar issue but the threads were years old. However I found out there is actually another way of moving carePosition to end, using [InputField.MoveTextEnd](https://docs.unity3d.com/2019.1/Documentation/ScriptReference/UI.InputField.MoveTextEnd.html) method.

 I changed the code to use this method. Commit in the dev branch https://github.com/anarkila/DeveloperConsole/commit/764b06d3b42a0bdd0ee42a6005c1f13180b1aceb. Can you test it on your project?

**Comment by ndumais** [comment]
Hey, sorry was sick the past 3 days so took a bit of time to test it and follow up, but it seems like this method works better for some reason. I don't see any issues with that method, issue is seemingly fixed!

Also I don't think you get notifications when I post on closed issues right?
Updated issue #6 again!

**Comment by anarkila** [comment]
>Also I don't think you get notifications when I post on closed issues right?
Updated issue https://github.com/anarkila/DeveloperConsole/issues/6 again!

I didn't receive notification for this. I'm going to look this a bit later. 

That's great to hear this issue is now fixed. This seems like some sort of Unity bug but since I couldn't reproduce it myself, I can't make bug report. I'm going to close this issue.  Thanks for your testing!
